name: notes
description: Flutter notes project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^0.6.7
  cupertino_icons: ^0.1.3
  dartz: ^0.9.1
  flushbar: ^1.10.4
  flutter_bloc: ^6.0.1
  flutter_hooks: ^0.13.1
  freezed_annotation: ^0.11.0+1
  get_it: ^4.0.4
  google_sign_in: ^4.5.1
  hive_flutter: ^0.3.1
  injectable: ^1.0.4
  intl: ^0.16.1
  kt_dart: ^0.7.0+1
  logging: ^0.11.4
  path_provider: ^1.6.11
#   preview: 
  rxdart: ^0.24.1
  sign_in_with_apple: ^2.5.2
  uuid: ^2.2.0

  # Firebase & Auth
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_analytics: ^6.0.0
  firebase_crashlytics: ^0.1.4+1
  firebase_performance: ^0.4.0
  firebase_database: ^4.0.0
  firebase_storage: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^0.6.8
  bloc_test: ^7.0.0
  build_runner: null
  flappy_translator: ^1.2.2
  flutter_launcher_icons: ^0.7.5
  freezed: ^0.11.5
  hive_generator: ^0.7.1
  injectable_generator: ^1.0.4
  json_serializable: ^3.3.0
  lint: ^1.2.0

flappy_translator:
  input_file_path: "notes_language - language.csv"
  output_dir: "lib/lang"
  file_name: "i18n"
  class_name: "I18n"
  delimiter: ","
  start_index: 1
  depend_on_context: true
  use_single_quotes: false
  replace_no_break_spaces: false

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/lizard.png"
  image_path: "assets/lizard.png"

flutter:
  uses-material-design: true
  assets:
    - assets/

